version: 1.0.{build}

environment:
  matrix: 
  - job_name: Windows build
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - job_name: Ubuntu build
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  - job_name: MacOS build
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

  for:
  -
    matrix:
      only:
        - job_name: Windows build
          JAVA_HOME: C:\Program Files\Java\jdk14          
    build_script:
    - cmd: gradlew jpackage   
     artifacts:
         - path: build/jpackage/Newton-0.0.1-x64.msi
    
    matrix:
      only:
        - job_name: Ubuntu build
          stack: jdk 14  
    build_script:
    - sh: ./gradlew jpackage    
     artifacts:
         - path: build/jpackage/newton_0.0.1_ubuntu_amd64.deb
 matrix:
      only:
        - job_name: macOS build
          stack: jdk 14
    build_script:
    - sh: ./gradlew jpackage    
     artifacts:
         - path: build/jpackage/Newton-0.0.1-MacOS.dmg

deploy:
- provider: GitHub
  release: Newton-v$(appveyor_build_version)
  auth_token:
    secure: UUbCGIF4aAb+8YcVkN9DqKaqdlvFQ4wIhF8Cac9oTXes6z5de29/TQWmoqgeyvyt
  repository: ncpproject/Newton
  on:
    APPVEYOR_REPO_TAG: true
