dist: bionic

language: java

jdk:
  - openjdk14
  
os:
  - linux
  - osx  

before_install:
 - if [ $TRAVIS_OS_NAME = osx ]; then sudo apt-get update -y ; fi
 - if [ $TRAVIS_OS_NAME = osx ]; then sudo apt-get install -y fakeroot ; fi
 - chmod +x gradlew
 
script:
 - ./gradlew check
 - ./gradlew jpackage
