dist: bionic

language: java

jdk:
  - openjdk14
  
os:
  - linux
  - osx  
  - windows

before_install:
 - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -y ; fi
 - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y fakeroot ; fi
 - chmod +x gradlew
 
script:
 - gradle check
 - gradle jpackage
