dist: bionic
language: java
addons:
  apt:
    packages:
      - gradle

gradle check

before_install:
  - sudo apt-get update
  - wget --no-check-certificate -c --header  "Cookie: oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/14+36/076bab302c7b4508975440c56f6cc26a/jdk-14_linux-x64_bin.deb"
  - sudo apt install ./jdk-14_linux-x64_bin.deb -y
  - cat <<EOF | sudo tee /etc/profile.d/jdk14.sh
  - export JAVA_HOME=/usr/lib/jvm/jdk-14
  - export PATH=\$PATH:\$JAVA_HOME/bin
  - EOF
  - source /etc/profile.d/jdk14.sh
  - java -version

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
